# to replace main page with content/_index.md: $ mkdir -p layouts && cp themes/BMFW/layouts/_default/single.html layouts/index.html

# git submodule add https://github.com/hell-hunt/BMFW.git themes/BMFW
baseURL: https://bestmotherfucking.website/
title: Best Motherfucking Website
languageCode: et-ee
defaultContentLanguage: et
pluralizeListTitles: false
theme: BMFW

# all this section to add JSON feed
mediaTypes:
  application/feed+json:
    suffixes:
      - json
outputFormats:
  jsonfeed:
    mediaType: application/feed+json
    baseName: feed
    rel: alternate
    isPlainText: true
outputs:
  home:
   - HTML
   - jsonfeed
   - RSS
  taxonomy:
    - HTML
    - jsonfeed
    - RSS
  term:
    - HTML
    - jsonfeed
    - RSS

markup:
  highlight:
    noclasses: false

params:
  readingTime: false # show '8 minute read'
  titleAnchors: false # Left of titles, an anchor to the title will appear.
  preLengthCap: false # Cap the length of preformatted blocks (in markdown with ```)

menu:
  main:
  - identifier: home
    name: bmfw
    url: /
#    pre:
#    post:
    params:
      underline: false
      separator: "<br>"
      activeHighlight: false # does not turn bold when url is /
    weight: -1000
  - identifier: original
    name: Original
    url: https://bestmotherfucking.website/
  - identifier: theme
    name: Hugo theme
    url: https://github.com/hell-hunt/BMFW
